name: Build and deploy to GitHub Pages

on:
  push:
    branches: [09-3-questions]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1

      - name: Create env file ðŸ”§
        run: |
          touch .env
          echo PASSWORD = \"${{secrets.PASSWORD}}\" >> .env
          echo ${{secrets.PASSWORD}}

      - name: Install and Build ðŸ”§
        run: |
          npm i
          npm run build

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
